In [51]:
import numpy as np

In [52]:
buckets = 3
tiles = 4

In [53]:
theta1 = np.linspace(0, 360, buckets+1) #.repeat(buckets)
dtheta1 = np.linspace(0, 180, buckets+1) #.repeat(buckets)

#theta2 = np.linspace(0, 360, 20)
#dtheta2 = np.linspace(0, 360, 20)

In [54]:
t1 = np.vstack((theta1, dtheta1)).T #, theta2, dtheta2)).T
t2 = t1+20
t3 = t2+20

In [55]:
t1

array([[  0.,   0.],
       [120.,  60.],
       [240., 120.],
       [360., 180.]])

In [56]:
t2

array([[ 20.,  20.],
       [140.,  80.],
       [260., 140.],
       [380., 200.]])

In [57]:
t3

array([[ 40.,  40.],
       [160., 100.],
       [280., 160.],
       [400., 220.]])

In [58]:
vec = np.array([260, 170])

In [59]:
bucket_list = np.arange(1, buckets**2+1).reshape((buckets, buckets))
bucket_nr = np.argmax(t1-vec >= 0, axis=0)-1
bucket_list[bucket_nr[0]][bucket_nr[1]]

9

In [60]:
bucket_list = np.arange(1, buckets**2+1).reshape((buckets, buckets))
bucket_nr = np.argmax(t2-vec >= 0, axis=0)-1
bucket_list[bucket_nr[0]][bucket_nr[1]]

6

In [50]:
bucket_list = np.arange(0, buckets**2).reshape((buckets, buckets))
bucket_nr = np.argmax(t3-vec >= 0, axis=0)-1
bucket_list[bucket_nr[0]][bucket_nr[1]]

5