In [40]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [41]:
from gameworlds.hex_world import HexState, HexAction, is_final_move, neighbors
import numpy as np
from config import  Config
import random
from rl import ReinforcementLearningAgent
import time
from IPython.display import clear_output


In [42]:
flat = np.zeros(Config.k**2 + 1)
flat[0] = 1


for _ in range(2000):
    state = HexState.from_array(flat)
    
    while not state.is_final_state:

        move = random.choice(state.get_legal_actions())

        state = state.do_action(move)
        # state.plot(labels=True)
        # time.sleep(0.5)
        # clear_output(wait=True)
    # print(f"Player {-state.player} won!")
    

In [43]:
rlAgent = ReinforcementLearningAgent()

3


In [52]:
rlAgent.train()

Episode 0
Move 1:
D:  [0.02 0.08 0.12 0.2  0.16 0.2  0.08 0.06 0.08]
Board:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Doing:  HexAction(row=1, col=2)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.562195 to fit


Move 2:
D:  [0.01785714 0.01785714 0.01785714 0.57142857 0.01785714 0.
 0.01785714 0.01785714 0.32142857]
Board:  [[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Doing:  HexAction(row=2, col=1)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.919363 to fit


Move 3:
D:  [0.02 0.1  0.02 0.26 0.24 0.1  0.1  0.06 0.1 ]
Board:  [[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=0, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.634233 to fit


Move 4:
D:  [0.   0.08 0.02 0.18 0.42 0.04 0.1  0.06 0.1 ]
Board:  [[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=1, col=1)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.686522 to fit


Move 5:
D:  [0.04347826 0.04347826 0.04347826 0.04347826 0.         0.04347826
 0.72463768 0.02898551 0.02898551]
Board:  [[ 1.  0.  0.]
 [ 0. -1.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=2, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.779554 to fit


Move 6:
D:  [0.0625     0.0625     0.09375    0.14583333 0.         0.09375
 0.         0.52083333 0.02083333]
Board:  [[ 1.  0.  0.]
 [ 0. -1.  1.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=0, col=2)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.514816 to fit


Move 7:
D:  [0.03921569 0.35294118 0.         0.19607843 0.15686275 0.11764706
 0.         0.01960784 0.11764706]
Board:  [[ 1.  0. -1.]
 [ 0. -1.  1.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=1, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.650255 to fit


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.747269 to fit


Move 2:
D:  [0.01785714 0.01785714 0.01785714 0.01785714 0.80357143 0.
 0.01785714 0.01785714 0.08928571]
Board:  [[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Doing:  HexAction(row=2, col=1)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.966008 to fit


Move 3:
D:  [0.02 0.08 0.26 0.24 0.14 0.04 0.08 0.02 0.12]
Board:  [[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=0, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.630038 to fit


Move 4:
D:  [0.   0.08 0.02 0.48 0.06 0.14 0.08 0.06 0.08]
Board:  [[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=1, col=1)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.761687 to fit


Move 5:
D:  [0.01923077 0.13461538 0.15384615 0.32692308 0.         0.09615385
 0.13461538 0.01923077 0.11538462]
Board:  [[ 1.  0.  0.]
 [ 0. -1.  1.]
 [ 0. -1.  0.]]
Doing:  HexAction(row=2, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.666646 to fit


Move 6:
D:  [0.01818182 0.03636364 0.01818182 0.34545455 0.32727273 0.12727273
 0.         0.01818182 0.10909091]
Board:  [[ 1.  0.  0.]
 [ 0. -1.  1.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=0, col=2)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.760891 to fit


Move 7:
D:  [0.02 0.22 0.   0.1  0.34 0.1  0.   0.12 0.1 ]
Board:  [[ 1.  0. -1.]
 [ 0. -1.  1.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=1, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.596838 to fit


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.546481 to fit


Move 2:
D:  [0.01818182 0.01818182 0.01818182 0.01818182 0.61818182 0.14545455
 0.         0.01818182 0.14545455]
Board:  [[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
Doing:  HexAction(row=2, col=1)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.755157 to fit


Move 3:
D:  [0.06 0.08 0.12 0.16 0.28 0.1  0.12 0.06 0.02]
Board:  [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=0, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.567021 to fit


Move 4:
D:  [0.         0.01923077 0.09615385 0.36538462 0.19230769 0.15384615
 0.07692308 0.01923077 0.07692308]
Board:  [[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=0, col=2)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.625193 to fit


Move 5:
D:  [0.         0.01851852 0.         0.01851852 0.01851852 0.07407407
 0.83333333 0.01851852 0.01851852]
Board:  [[ 1.  0. -1.]
 [ 0.  0.  0.]
 [ 1. -1.  0.]]
Doing:  HexAction(row=1, col=0)


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.867471 to fit


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.