In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from gameworlds.hex_world import HexState, HexAction, is_final_move, neighbors
import numpy as np
from config import  Config
import random

In [3]:
flat = np.zeros(Config.k**2 + 1)
flat[0] = 1

state = HexState.from_array(flat)
state

HexState(is_final_state=False, player=1, board=array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]]), k=7)

In [4]:
moves = state.get_legal_actions()
move = random.choice(moves)
move

HexAction(row=3, col=0)

In [5]:
state = state.do_action(move)
state

HexState(is_final_state=False, player=-1, board=array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]]), k=7)

In [6]:
state.board

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
neighbors

In [8]:
flat = np.zeros(Config.k**2 + 1)
flat[0] = 1

boards= []

for _ in range(1000):
    state = HexState.from_array(flat)
    
    while not state.is_final_state:

        move = random.choice(state.get_legal_actions())

        state = state.do_action(move)
    boards.append(state.board.copy())
    

In [9]:
boards


[array([[-1., -1., -1.,  1.,  1., -1.,  1.],
        [-1.,  1., -1.,  1., -1.,  1., -1.],
        [ 0.,  0.,  1.,  1.,  1., -1.,  0.],
        [ 0.,  0.,  1.,  0.,  1.,  1., -1.],
        [-1.,  1., -1.,  1.,  0., -1.,  1.],
        [ 0.,  1.,  1.,  0.,  0., -1.,  1.],
        [-1., -1., -1., -1., -1.,  0.,  1.]]),
 array([[-1.,  1.,  1.,  1.,  1., -1., -1.],
        [-1.,  1.,  0.,  1.,  1., -1.,  0.],
        [ 0., -1.,  1., -1.,  0.,  1., -1.],
        [ 0.,  0.,  1.,  1.,  1., -1., -1.],
        [ 1.,  1., -1.,  1.,  0., -1.,  1.],
        [ 1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 1., -1., -1., -1., -1.,  1., -1.]]),
 array([[-1., -1., -1., -1.,  1.,  0., -1.],
        [-1.,  0., -1., -1., -1., -1.,  1.],
        [-1.,  0.,  1.,  1.,  0.,  1.,  0.],
        [-1.,  1.,  1., -1.,  1.,  1.,  0.],
        [-1.,  0.,  0., -1.,  1.,  0.,  0.],
        [-1.,  1.,  1.,  0., -1.,  0.,  1.],
        [ 0.,  1.,  0.,  1.,  1.,  0.,  1.]]),
 array([[-1., -1.,  1.,  0.,  1.,  1.,  1.],
    

In [11]:
state

HexState(is_final_state=True, player=-1, board=array([[-1.,  0.,  1.,  0., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1., -1.],
       [-1., -1.,  0., -1.,  1., -1., -1.],
       [ 1., -1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  0.,  0., -1.,  0.,  0.],
       [ 1., -1.,  0.,  1., -1., -1.,  1.],
       [ 1., -1.,  1.,  1., -1., -1., -1.]]), k=7)